services:
  db:
    platform: linux/amd64
    image: mysql:5.5.62
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tng_db6
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
  web:
    platform: linux/amd64
    build:
      context: web/
      dockerfile: Dockerfile
    links:
      - "db"
    ports:
      - 8888:80
    volumes:
      - ./web/data:/var/www/html/
  pma:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - "db"
    ports:
      - 8889:80
